version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v2.0.1
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            # /scripts/build-image.sh web3f/edgeware .
            echo "Not building image, using latest one"

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

#  publishImage:
#    docker:
#      - image: web3f/ci-commons:v2.0.1
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          command: |
#            /scripts/publish-image.sh web3f/edgeware

  deploy:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          environment:
            HELM_ENV: production
            GCP_REGION: europe-west3
          command: |
            /scripts/deploy.sh -c engineering

workflows:
  version: 2
  test_and_deploy:
    jobs:
#      - buildImage:
#          filters:
#            tags:
#              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
#          requires:
#            - buildImage
#      - publishImage:
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /v[0-9]+(\.[0-9]+)*/
#          requires:
#            - integrationTests
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
#            - publishImage
